apiVersion: v1
kind: Service
metadata:
  name: eric-oss-byos-docker
  labels:
    app.kubernetes.io/name: byos-docker
    app.kubernetes.io/instance: {{ .Release.Name }} # Sets service name
  annotations:
{{- include "eric-oss-restsim-byos.annotations" . | indent 4 }}
spec:
  type: LoadBalancer
{{- if .Values.global }}
  {{- if .Values.global.internalIPFamily }}
  ipFamilies: [{{ .Values.global.internalIPFamily }}]
  {{- end }}
{{- end }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: byos-docker
    app.kubernetes.io/instance: {{ .Release.Name }}
