{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "eric-oss-byos-buildmanager.name" . }}-postgres-policy
  labels:
    {{- include "eric-oss-byos-buildmanager.labels" . | indent 4 }}
  annotations:
{{- include "eric-oss-byos-buildmanager.annotations" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: porter-postgres
  policyTypes:
  - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app.kubernetes.io/name: eric-oss-byos-buildmanager
      - namespaceSelector:
          matchLabels:
            namespace: porter-service
      ports:
      - port: 5432
        protocol: TCP
{{- end }}
{{- end }}
{{- end }}
