apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-oss-byos-buildmanager.name" . }}
  labels: {{- include "eric-oss-byos-buildmanager.labels" . | trim | nindent 4 }}
  annotations: {{- include "eric-oss-byos-buildmanager.annotations" . | trim | nindent 4 }}
automountServiceAccountToken: false
